version: "3.4"


services:
  my-django-project:
    image: my-django-project
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=MyDjangoSite.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
      - DJANGO_COLLECT_STATIC=1
    restart: unless-stopped
    container_name: my-django-project

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static:ro
      - ./nginx/mysite.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - my-django-project
    restart: unless-stopped
    container_name: nginx


volumes:
  static_volume:
